package engage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;


/**
 * Overwrite the autogenerated methods for rest methods
 */
@RestController
public class CategoryController {

    @Autowired
    private CategoryRepository categoryRepo;

//    @PostMapping("/categories")
//    public Category createCategory(@Valid @RequestBody Category categoryRequest) {
//    }
//
//    @GetMapping("/categories")
//    public Page<Category> getAllCategories(Pageable pageable) {
//        return categoryRepository.findAll(pageable);
//    }
//
//    @PutMapping("/categories/{categoryId}")
//    public Category updateCategory(@PathVariable Long categoryId, @Valid @RequestBody Category categoryRequest) {
//    }
//
//
//    @DeleteMapping("/categories/{categoryId}")
//    public ResponseEntity<?> deleteCategory(@PathVariable Long categoryId) {
//        return categoryRepository.findById(categoryId).map(category -> {
//            categoryRepository.delete(category);
//            return ResponseEntity.ok().build();
//        }).orElseThrow(() -> new ResourceNotFoundException("CategoryId " + categoryId + " not found"));
//    }

}